** What is this ?

I have pulled together a number of resources from across the internet in emacs
org file format.

- D&D 5E SRD REmastered?
- (Must find the original emacs org file).

This is an adaptation of the D&D 5E SRD REformatted in Emacs org file format,
I'm also adapting any current rule books that I find into a usable org file format
that helps me organize and run my games.

* I found an error, can you fix it ?

While you can make an issue and tell me what is wrong, I would prefer to have a
PR fixing the issue.

** Why Org file format?

Frankly I use emacs for everything, I dont want to learn another file format, maybe
markdown is great, its not for me, you can fork this repo and do what you need.


** My org file complains about missing PDF's ?

In each of my campaigns I have related pdfs.  I use the org-mode links to the relevant
pdf files and pages to directly jump to that area when required.  You can get a pdf
and put it in the directory and it -should- work correctly.

I would strongly reccomend owning the pdf / book as otherwise we're depriving the authors
and creators involved from their deserved income.

** I want to correct / add a campaign.

Go ahead and submit a PR.  I will have final say over correctness.

** You used something I've created !

Because some of these resources have been pulled together over a long period of time,
if I have inadvertedly used your content, I am sorry and will do what I can to credit or
remove it if you feel its wrong.


© 2015 Wizards. All Rights Reserved. Dungeons & Dragons® is a
trademark[s] of Wizards of the Coast. For more information about Wizards
of the Coast or any of Wizards' trademarks or other intellectual
property, please visit their website at
[[http://www.wizards.com][www.wizards.com]].
